installCRDs: true
replicaCount: 2
prometheus:
  enabled: false
webhook:
  timeoutSeconds: 5
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

serviceAccount:
  create: true
  name: cert-manager
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::906766085108:role/petclinic-cluster-cert-manager
